import Head from "next/head";
import Link from "next/link";
import { sanityClient, urlFor } from "../lib/sanity";
import { groq } from "next-sanity";


const recipesQuery = groq`*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
}`;

export default function Home({ recipes }) {
  console.log(recipes)
  return (
    <div>
      <Head>
        <title>Paris Bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Paris Bar</h1>
      <h2>drinks menu</h2>
      <ul className="recipes-list">
        {recipes.map((recipe) => (
          <li key={recipe._id} className="recipe-card">
            <Link href="">
              <a>
              <img src={urlFor(recipe.mainImage).url()} alt={recipe.name} />
                <span>{recipe.name}</span>
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);

  return { props: { recipes } };
}
